name: adivinheganhe
description: "Projeto app nativo do Adivinhe e Ganhe."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  http: ^1.1.0
  webview_flutter: ^4.2.1
  flutter_secure_storage: ^9.2.4  
  flutter_html: ^3.0.0
  chewie: ^1.7.0
  video_player: ^2.7.0
  open_filex: ^4.3.4
  url_launcher: ^6.2.5
  just_audio: ^0.9.42
  firebase_core: ^2.25.0
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^19.4.1  # <-- Atualizado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
